require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
