after_success: bundle exec codeclimate-test-report
branches:
  only:
    - master
bundler_args: --without development
env:
  global:
    secure: xel5mj9lZv22Cq2eyLI5vzrYQqkHUCdXq6bRJMDAjsqQ0ldWSAlImmArTb/OUZ9W7E4qeUYdZJdS9ayAyRjBog3rtSYBBAQDdoK2RmDNOv+8t5NDSAfMdtpDpZonr1MUETXmcfCWiqp69uBs9rFTM1CXSdlDBcpBUkSI3QOlPhE=
gemfile: Gemfile.travis
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-19mode
script: bundle exec rspec
sudo: false
