language: ruby
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - jruby-1.7.19
  - rbx
branches:
  only:
    - master
bundler_args: --without development
script: bundle exec rspec
gemfile: Gemfile.travis
addons:
  code_climate:
    repo_token:
