branches:
  only:
    - master
bundler_args: --without development
gemfile: Gemfile.travis
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.3
  - 2.6.0
  - jruby-19mode
script: bundle exec rspec
sudo: false
